InstagramLite/Models/DbPost.cs
using System;
using Microsoft.AspNetCore.Identity;

namespace InstagramLite.Models
{
    public class DbPost
    {
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UserId { get; set; }
        public virtual IdentityUser User { get; set; }
        public int Likes { get; set; }
    }
}

InstagramLite/Models/ErrorViewModel.cs
using System;

namespace InstagramLite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InstagramLite/Models/Post.cs
using System;
using Microsoft.AspNetCore.Identity;

namespace InstagramLite.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UserId { get; set; }
        public virtual IdentityUser User { get; set; }
        public int Likes { get; set; }
    }
}

InstagramLite/ViewModels/PostViewModel.cs
using Microsoft.AspNetCore.Http;

namespace InstagramLite.ViewModels
{
    public class PostViewModel
    {
        public string Description { get; set; }
        public IFormFile Photo { get; set; }
    }
}

InstagramLite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using InstagramLite.Models;

namespace InstagramLite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InstagramLite/Controllers/PostsController.cs
using System;
using System.IO;
using System.Linq;
using AutoMapper;
using InstagramLite.Infrastructure;
using InstagramLite.Models;
using InstagramLite.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V3.Pages.Internal.Account;
using Microsoft.AspNetCore.Mvc;

namespace InstagramLite.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly Random _random;
        private readonly IWebHostEnvironment _environment;

        public PostsController(IUnitOfWork uow, IMapper mapper, UserManager<IdentityUser> userManager, 
            Random random, IWebHostEnvironment environment)
        {
            _uow = uow;
            _mapper = mapper;
            _userManager = userManager;
            _random = random;
            _environment = environment;
        }

        public IActionResult Index()
        {
            var posts = _uow.Posts.GetAll().OrderByDescending(x => x.CreatedDate);

            return View(posts);
        }
        public IActionResult Index2()
        {
            var posts = _uow.DbPosts.GetAll().OrderByDescending(x => x.CreatedDate);

            return View(posts);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var model = _mapper.Map<Post>(viewModel);
                model.CreatedDate = DateTime.Now;

                //var photoId = _random.Next(1, 1000);

                //model.Photo = $"https://picsum.photos/id/{photoId}/300/200";
                model.UserId = _userManager.GetUserId(HttpContext.User);
                model.Likes = 0;

                if (viewModel.Photo != null)
                {
                    var path = "/Files/" + viewModel.Photo.FileName;

                    using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                    {
                        viewModel.Photo.CopyTo(fileStream);
                    }

                    model.Photo = path;
                }

                var createdPost = _uow.Posts.Create(model);
                _uow.Save();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }


        public IActionResult CreateDbPost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateDbPost(PostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                DbPost model = new DbPost();
                model.Description = viewModel.Description;
                model.CreatedDate = DateTime.Now;
                model.UserId = _userManager.GetUserId(HttpContext.User);
                model.Likes = 0;

                if (viewModel.Photo != null)
                {
                    byte[] image;

                    using (var binaryReader = new BinaryReader(viewModel.Photo.OpenReadStream()))
                    {
                        image = binaryReader.ReadBytes((int)viewModel.Photo.Length);
                    }

                    model.Photo = image;
                }

                var createdPost = _uow.DbPosts.Create(model);
                _uow.Save();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }




        [HttpPost]
        public JsonResult Like(int postId)
        {
            var post = _uow.Posts.Get(postId);
            post.Likes += 1;

            _uow.Save();

            return Json(new {post.Likes});
        }
    }
}

InstagramLite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InstagramLite/Views/Posts/Create.cshtml
@model InstagramLite.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PostViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @*<input asp-for="Description" class="form-control" />*@
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Photo"></label>
                <input type="file" name="Photo" class="form-control"/>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InstagramLite/Views/Posts/CreateDbPost.cshtml
@model InstagramLite.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PostViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateDbPost" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @*<input asp-for="Description" class="form-control" />*@
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Photo"></label>
                <input type="file" name="Photo" class="form-control"/>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InstagramLite/Views/Posts/Index.cshtml
@using InstagramLite.Infrastructure
@model IEnumerable<InstagramLite.Models.Post>

@{
    ViewData["Title"] = "Index";
}

<h1>News feed</h1>

<p>
    <a asp-action="Create">New Post</a>
</p>


<div class="align-content-center">
    @foreach (var post in Model)
    {
        <div class="card" style="width: 500px !important; margin: 0 auto;">
            <h6 class="card-header">@post.User.Email.Substring(0, post.User.Email.IndexOf('@'))</h6>
            <img class="card-img-top" src="@post.Photo" alt="Card image cap">
            <div class="card-body">
                <div style="margin-bottom: 5px;">
                    <img class="likeBtn" style="cursor: pointer;" src="images/like.png" width="27" alt="Like" data-id="@post.Id"
                         />
                    <span class="likesCount">@post.Likes</span><span> likes</span>
                </div>
                <p class="card-text"><strong>@post.User.Email.Substring(0, post.User.Email.IndexOf('@')) </strong>@post.Description</p>
                <p class="card-text"><small class="text-muted">@post.CreatedDate.ToString("MMMM dd")</small></p>
            </div>
        </div>
        <br />
    }
</div>


@section Scripts
{
    <script>
        $(".likeBtn").on("click",
            function(e) {
                console.log($(this).attr("data-id"));

                var currentElement = $(this);

                var dataId = $(this).attr("data-id");

                $.ajax({
                    type: "POST",
                    url: "/Posts/Like",
                    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    data: {postId: parseInt(dataId)},
                    success: function(data) {
                        //console.log(data.likes);
                        //$(this).closest('span').text(data.likes);
                        console.log();
                        currentElement.next().html(data.likes);

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        
                        console.log(jqXHR.responseText);
                        console.log(textStatus);
                        console.log(errorThrown);
                    }
                });
            });
    </script>
}


@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Likes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Photo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Likes)
                </td>
            </tr>
        }
    </tbody>
</table>*@

InstagramLite/Views/Posts/Index2.cshtml
@using InstagramLite.Infrastructure
@model IEnumerable<InstagramLite.Models.DbPost>

@{
    ViewData["Title"] = "Index";
}

<h1>News feed</h1>

<p>
    <a asp-action="CreateDbPost">New Post</a>
</p>


<div class="align-content-center">
    @foreach (var post in Model)
    {
    <div class="card" style="width: 500px !important; margin: 0 auto;">
        <h6 class="card-header">@post.User.Email.Substring(0, post.User.Email.IndexOf('@'))</h6>
        <img class="card-img-top" src="data:image/jpeg;base64,@(Convert.ToBase64String(post.Photo))" alt="another image"/>
        <div class="card-body">
            <div style="margin-bottom: 5px;">
                <img class="likeBtn" style="cursor: pointer;" src="/images/like.png" width="27" alt="Like" data-id="@post.Id" />
                <span class="likesCount">@post.Likes</span><span> likes</span>
            </div>
            <p class="card-text"><strong>@post.User.Email.Substring(0, post.User.Email.IndexOf('@')) </strong>@post.Description</p>
            <p class="card-text"><small class="text-muted">@post.CreatedDate.ToString("MMMM dd")</small></p>
        </div>
    </div>
        <br />
    }
</div>


@section Scripts
{
    <script>
        $(".likeBtn").on("click",
            function(e) {
                console.log($(this).attr("data-id"));

                var currentElement = $(this);

                var dataId = $(this).attr("data-id");

                $.ajax({
                    type: "POST",
                    url: "/Posts/Like",
                    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    data: {postId: parseInt(dataId)},
                    success: function(data) {
                        //console.log(data.likes);
                        //$(this).closest('span').text(data.likes);
                        console.log();
                        currentElement.next().html(data.likes);

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        
                        console.log(jqXHR.responseText);
                        console.log(textStatus);
                        console.log(errorThrown);
                    }
                });
            });
    </script>
}


@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Likes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Photo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Likes)
                </td>
            </tr>
        }
    </tbody>
</table>*@

InstagramLite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InstagramLite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InstagramLite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InstagramLite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>